enum DsrcMsgId {
  reservedMessageId_D(0), 
  alaCarteMessage_D(1), 
  basicSafetyMessage_D(2), 
  basicSafetyMessageVerbose_D(3), 
  commonSafetyRequest_D(4), 
  emergencyVehicleAlert_D(5), 
  intersectionCollision_D(6), 
  mapData_D(7), 
  nmeaCorrections_D(8), 
  probeDataManagement_D(9), 
  probeVehicleData_D(10), 
  roadSideAlert_D(11), 
  rtcmCorrections_D(12), 
  signalPhaseAndTimingMessage_D(13), 
  signalRequestMessage_D(14), 
  signalStatusMessage_D(15), 
  travelerInformation_D(16), 
  uperFrame_D(17), 
  mapData(18), 
  signalPhaseAndTimingMessage(19), 
  basicSafetyMessage(20), 
  commonSafetyRequest(21), 
  emergencyVehicleAlert(22), 
  intersectionCollision(23), 
  nmeaCorrections(24), 
  probeDataManagement(25), 
  probeVehicleData(26), 
  roadSideAlert(27), 
  rtcmCorrections(28), 
  signalRequestMessage(29), 
  signalStatusMessage(30), 
  travelerInformation(31), 
  personalSafetyMessage(32), 
  roadSafetyMessage(33), 
  roadWeatherMessage(34), 
  probeDataConfigMessage(35), 
  probeDataReportMessage(36), 
  tollAdvertisementMessage(37), 
  tollUsageMessage(38), 
  tollUsageAckMessage(39), 
  cooperativeControlMessage_DSRCmsgID(40), 
  sensorDataSharingMessage(41), 
  maneuverSharingAndCoordinatingMessage_DSRCmsgID(42), 
  roadGeometryAndAttributes_DSRCmsgID(43), 
  personalSafetyMessage2(44), 
  trafficSignalPhaseAndTiming(45), 
  signalControlAndPrioritizationRequest(46), 
  signalControlAndPrioritizationStatus(47), 
  roadUserChargingConfigMessage(48), 
  roadUserChargingReportMessage(49), 
  trafficLightStatusMessage(50), 
  testMessage00(240), 
  testMessage01(241),   
  testMessage02(242),   
  testMessage03(243),   
  testMessage04(244),    
  testMessage05(245),   
  testMessage06(246),   
  testMessage07(247),   
  testMessage08(248),   
  testMessage09(249),   
  testMessage10(250),  
  testMessage11(251),   
  testMessage12(252),   
  testMessage13(253),   
  testMessage14(254),   
  testMessage15(255);



  final int code;
  const DsrcMsgId(this.code);
}



