/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:convert';
import 'dart:typed_data';

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/toll_usage_message/tum_data.dart';
import 'dart:ffi';

import 'package:ffi/ffi.dart';


class EncryptedTumData{
  late String encryptedTumData;
  late TumData? tumData;

  EncryptedTumData.fromOctetString(C.OCTET_STRING string){
    final Uint8List byteList = string.buf.asTypedList(string.size);
    encryptedTumData = byteList.map((b) => b.toRadixString(16).padLeft(2, '0')).join('');
  }

  EncryptedTumData(this.encryptedTumData, {this.tumData});

  void toC(Pointer<C.OCTET_STRING> pointer) {
    final c_encryptedTumData = pointer.ref;

    // Free previous buffer if needed
    if (c_encryptedTumData.buf != nullptr && c_encryptedTumData.size > 0) {
      calloc.free(c_encryptedTumData.buf);
      c_encryptedTumData.buf = nullptr;
    }

    // Convert hex string to bytes
    final bytes = <int>[];
    for (int i = 0; i < encryptedTumData.length; i += 2) {
      bytes.add(int.parse(encryptedTumData.substring(i, i + 2), radix: 16));
    }

    if (bytes.isEmpty) {
      c_encryptedTumData.size = 0;
      c_encryptedTumData.buf = nullptr;
      return; // Just return without a value
    }

    // Allocate new buffer - fix deprecated allocation method
    c_encryptedTumData.buf = calloc<Uint8>(bytes.length);
    for (int i = 0; i < bytes.length; i++) {
      c_encryptedTumData.buf[i] = bytes[i];
    }
    c_encryptedTumData.size = bytes.length;
  }
}