/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_usage_message/last_toll_point_info.dart'; 
import 'package:ffi/ffi.dart';

class LastTollPointInfos{
  late List<LastTollPointInfo> lastTollPointInfos = [];
  LastTollPointInfos.fromC(C.LastTollPointInfos value) {
    lastTollPointInfos = [];
    for (int i = 0; i < value.list.count; i++) {
        lastTollPointInfos.add(LastTollPointInfo.fromC(value.list.array[i].ref));
    }
  }

  void toC(Pointer<C.LastTollPointInfos> pointer) {
    final c_lastTollPointInfos = pointer.ref;

    // Clean up existing allocations first
    _cleanupExistingAllocations(c_lastTollPointInfos);

    // Zero-initialize the entire struct first
    pointer.cast<Uint8>().asTypedList(sizeOf<C.LastTollPointInfos>()).fillRange(0, sizeOf<C.LastTollPointInfos>(), 0);

    // Handle empty list
    if (lastTollPointInfos.isEmpty) {
      c_lastTollPointInfos.list.count = 0;
      c_lastTollPointInfos.list.array = nullptr;
      return;
    }

    // Set count directly on the existing struct
    c_lastTollPointInfos.list.count = lastTollPointInfos.length;
    
    // Allocate array of pointers
    final arrayPtr = calloc<Pointer<C.LastTollPointInfo>>(lastTollPointInfos.length);

    for (int i = 0; i < lastTollPointInfos.length; i++) {
      final itemPtr = calloc<C.LastTollPointInfo>();
      // Zero-initialize nested struct
      itemPtr.cast<Uint8>().asTypedList(sizeOf<C.LastTollPointInfo>()).fillRange(0, sizeOf<C.LastTollPointInfo>(), 0);
      lastTollPointInfos[i].toC(itemPtr);
      arrayPtr[i] = itemPtr;
    }

    // Set array pointer directly on the existing struct
    c_lastTollPointInfos.list.array = arrayPtr;
  }

  // Add cleanup method
  void _cleanupExistingAllocations(C.LastTollPointInfos c_lastTollPointInfos) {
    if (c_lastTollPointInfos.list.array != nullptr) {
      // Free individual items first
      for (int i = 0; i < c_lastTollPointInfos.list.count; i++) {
        if (c_lastTollPointInfos.list.array[i] != nullptr) {
          calloc.free(c_lastTollPointInfos.list.array[i]);
        }
      }
      // Free the array itself
      calloc.free(c_lastTollPointInfos.list.array);
      c_lastTollPointInfos.list.array = nullptr;
    }
    c_lastTollPointInfos.list.count = 0;
  }
}
