/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_charger_info.dart'; 
import 'package:ffi/ffi.dart';

class LastTollPointInfo {
    late TollChargerInfo tollChargerInfo; 
    late DDateTime timeStamp; 
    LastTollPointInfo.fromC(C.LastTollPointInfo c_obj){
        tollChargerInfo = TollChargerInfo.fromC(c_obj.tollChargerInfo);
        timeStamp = DDateTime.fromC(c_obj.timeStamp);
    }

    void toC(Pointer<C.LastTollPointInfo> pointer) {
      final c_info = pointer.ref;
      
      // Zero-initialize the entire struct first
      pointer.cast<Uint8>().asTypedList(sizeOf<C.LastTollPointInfo>()).fillRange(0, sizeOf<C.LastTollPointInfo>(), 0);

      // Handle tollChargerInfo
      final tollChargerInfoPtr = calloc<C.TollChargerInfo>();
      tollChargerInfo.toC(tollChargerInfoPtr);
      c_info.tollChargerInfo = tollChargerInfoPtr.ref;

      // Handle timeStamp
      final timeStampPtr = calloc<C.DDateTime>();
      timeStamp.toC(timeStampPtr);
      c_info.timeStamp = timeStampPtr.ref;
    }
}