/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j2735/2024/common/elevation.dart';
import 'package:asn1_plugin/j2735/2024/common/lane_id.dart';
import 'package:asn1_plugin/j2735/2024/common/latitude.dart';
import 'package:asn1_plugin/j2735/2024/common/longitude.dart';
import 'dart:ffi';
import 'package:ffi/ffi.dart';


class LocAndTimeStamp {
    late Latitude latitude; 
    late Longitude longitude; 
    Elevation? elevation; 
    late DDateTime timeStamp; 
    LaneID? currentLane; 
    LocAndTimeStamp.fromC(C.LocAndTimeStamp c_obj){
        latitude = Latitude(c_obj.latitude);
        longitude = Longitude(c_obj.longitude);
        if(c_obj.elevation.address != 0){
            elevation = Elevation(c_obj.elevation.value);
        }

        timeStamp = DDateTime.fromC(c_obj.timeStamp);
        if(c_obj.currentLane.address != 0){
            currentLane = LaneID(c_obj.currentLane.value);
        }
    }

    void toC(Pointer<C.LocAndTimeStamp> pointer) {
      final c_locAndTimeStamp = pointer.ref;
      
      c_locAndTimeStamp.latitude = latitude.latitude;
      c_locAndTimeStamp.longitude = longitude.longitude;

      if (elevation != null) {
        final elevationPtr = calloc<Int32>();
        elevationPtr.value = elevation!.elevation;
        c_locAndTimeStamp.elevation = elevationPtr.cast<Long>();
      } else {
        c_locAndTimeStamp.elevation = nullptr;
      }

      final timeStampPtr = calloc<C.DDateTime>();
      timeStamp.toC(timeStampPtr);
      c_locAndTimeStamp.timeStamp = timeStampPtr.ref;

      if (currentLane != null) {
        final currentLanePtr = calloc<Int32>();
        currentLanePtr.value = currentLane!.laneID;
        c_locAndTimeStamp.currentLane = currentLanePtr.cast<Long>();
      } else {
        c_locAndTimeStamp.currentLane = nullptr;
      }

    }

    LocAndTimeStamp({required this.latitude, required this.longitude, int? elevation, required this.timeStamp, int? currentLane}){
        if(elevation != null){
            this.elevation = Elevation(elevation);
        }
        if(currentLane != null){
            this.currentLane = LaneID(currentLane);
        }
    }
}
