/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_usage_message/loc_and_time_stamp.dart';
import 'package:ffi/ffi.dart';

class LocAndTimeStamps {
    late List<LocAndTimeStamp> locAndTimeStamps;
    LocAndTimeStamps.fromC(C.LocAndTimeStamps value): super() {
        locAndTimeStamps = [];
        for (int i = 0; i < value.list.count; i++) {
            locAndTimeStamps.add(LocAndTimeStamp.fromC(value.list.array[i].ref));
        }
    }

    void toC(Pointer<C.LocAndTimeStamps> pointer) {
      final c_locAndTimeStamps = pointer.ref;

      // Free previous list if needed
      if (c_locAndTimeStamps.list.array != nullptr && c_locAndTimeStamps.list.count > 0) {
        for (int i = 0; i < c_locAndTimeStamps.list.count; i++) {
          calloc.free(c_locAndTimeStamps.list.array[i]);
        }
        calloc.free(c_locAndTimeStamps.list.array);
        c_locAndTimeStamps.list.array = nullptr;
        c_locAndTimeStamps.list.count = 0;
      }

      // Allocate new array
      final count = locAndTimeStamps.length;
      final arrayPtr = calloc<Pointer<C.LocAndTimeStamp>>(count);
      for (int i = 0; i < count; i++) {
        final stampPtr = calloc<C.LocAndTimeStamp>();
        //Zero-initialize nested struct
        stampPtr.cast<Uint8>().asTypedList(sizeOf<C.LocAndTimeStamp>()).fillRange(0, sizeOf<C.LocAndTimeStamp>(), 0);
        locAndTimeStamps[i].toC(stampPtr);
        arrayPtr[i] = stampPtr;
      }

      c_locAndTimeStamps.list.array = arrayPtr;
      c_locAndTimeStamps.list.count = count;
    }

    LocAndTimeStamps(this.locAndTimeStamps);
    
}
