/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j2735/2024/common/elevation.dart';
import 'package:asn1_plugin/j2735/2024/common/lane_id.dart';
import 'package:asn1_plugin/j2735/2024/common/latitude.dart';
import 'package:asn1_plugin/j2735/2024/common/longitude.dart';
import 'dart:ffi';


class LocAndTimeStamp {
    late Latitude latitude; 
    late Longitude longitude; 
    Elevation? elevation; 
    late DDateTime timeStamp; 
    LaneID? currentLane; 
    LocAndTimeStamp.fromC(C.LocAndTimeStamp c_obj){
        latitude = Latitude(c_obj.latitude);
        longitude = Longitude(c_obj.longitude);
        if(c_obj.elevation.address != 0){
            elevation = Elevation(c_obj.elevation.value);
        }

        timeStamp = DDateTime.fromC(c_obj.timeStamp);
        if(c_obj.currentLane.address != 0){
            currentLane = LaneID(c_obj.currentLane.value);
        }

    }
}
