/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j3217/2022/payment_fee.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_point_id.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/vehicle_types.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/last_toll_point_infos.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/loc_and_time_stamps.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_axles_and_weight_info.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_description.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_id.dart'; 
import 'package:ffi/ffi.dart';


class TollUserData {
    late DDateTime timestamp; 
    late String tspId; 
    late VehicleId vehicleId; 
    VehicleTypes? vehType; 
    VehicleDescription? vehicleDescription; 
    VehicleAxlesAndWeightInfo? vehAxlesAndWeight; 
    int? numOccupants; 
    TollPointID? entryTollPointId; 
    DDateTime? entryTimeStamp; 
    LocAndTimeStamps? locAndTimeStamps; 
    LastTollPointInfos? lastTollPoints = null; 
    PaymentFee? charge = null; 
    TollUserData.fromC(C.TollUserData c_obj){
        timestamp = DDateTime.fromC(c_obj.timeStamp);
        tspId = _oidBufferToString(c_obj.tspId);
        vehicleId = VehicleId.fromC(c_obj.vehicleId);
        if(c_obj.vehType.address != 0){
            vehType = VehicleTypes.values[c_obj.vehType.value];
        }

        if(c_obj.vehicleDescription.address != 0){
            vehicleDescription = VehicleDescription.fromC(c_obj.vehicleDescription.ref);
        }

        if(c_obj.vehAxlesAndWeight.address != 0){
            vehAxlesAndWeight = VehicleAxlesAndWeightInfo.fromC(c_obj.vehAxlesAndWeight.ref);
        }

        if(c_obj.numOccupants.address != 0){
            numOccupants = c_obj.numOccupants.value;
        }

        if(c_obj.entryTollPointId.address != 0){
            entryTollPointId = TollPointID(c_obj.entryTollPointId.value);
        }

        if(c_obj.entryTimeStamp.address != 0){
            entryTimeStamp = DDateTime.fromC(c_obj.entryTimeStamp.ref);
        }

        if(c_obj.locAndTimeStamps.address != 0){
            locAndTimeStamps = LocAndTimeStamps.fromC(c_obj.locAndTimeStamps.ref);
        }

        if(c_obj.lastTollPoints.address != 0){
            lastTollPoints = LastTollPointInfos.fromC(c_obj.lastTollPoints.ref);
        }

        if(c_obj.charge.address != 0){
            charge = PaymentFee.fromC(c_obj.charge.ref);
        }

    }

    C.TollUserData toC(Pointer<C.TollUserData> pointer) {
      final c_tollUserData = pointer.ref;
      
      // Clean up existing allocations first
      _cleanupExistingAllocations(c_tollUserData);
      
      final timestampPtr = calloc<C.DDateTime>();
      timestampPtr.cast<Uint8>().asTypedList(sizeOf<C.DDateTime>()).fillRange(0, sizeOf<C.DDateTime>(), 0);
      timestamp.toC(timestampPtr);
      c_tollUserData.timeStamp = timestampPtr.ref;

      _fillTspId(tspId, pointer);
      final vehicleIdPtr = calloc<C.TumVehicleId>();
      vehicleIdPtr.cast<Uint8>().asTypedList(sizeOf<C.TumVehicleId>()).fillRange(0, sizeOf<C.TumVehicleId>(), 0);
      vehicleId.toC(vehicleIdPtr);
      c_tollUserData.vehicleId = vehicleIdPtr.ref;

      // CORRECTED: VehicleTypes enum conversion
      if(vehType != null){
        final vehTypePtr = calloc<Int32>();
        vehTypePtr.value = (vehType!.index) + 1;
        c_tollUserData.vehType = vehTypePtr.cast<C.VehicleTypes_t>(); // Use VehicleTypes_t
      } else {
        c_tollUserData.vehType = nullptr;
      }

      if(vehicleDescription != null){
        final vehicleDescriptionPtr = calloc<C.VehicleDescription>();
        vehicleDescriptionPtr.cast<Uint8>().asTypedList(sizeOf<C.VehicleDescription>()).fillRange(0, sizeOf<C.VehicleDescription>(), 0);
        vehicleDescription!.toC(vehicleDescriptionPtr);
        c_tollUserData.vehicleDescription = vehicleDescriptionPtr;
      } else {
        c_tollUserData.vehicleDescription = nullptr;
      }

      // Handle numOccupants (similar pattern)
      if(numOccupants != null){
        final numOccupantsPtr = calloc<Int32>();  // Use Int32 instead
        numOccupantsPtr.value = numOccupants!;
        c_tollUserData.numOccupants = numOccupantsPtr.cast<Long>();
      } else {
        c_tollUserData.numOccupants = nullptr;
      }

      // Handle entryTollPointId
      if(entryTollPointId != null){
        final entryTollPointIdPtr = calloc<Int32>();  // Use Int32 instead
        entryTollPointIdPtr.value = entryTollPointId!.tollPointID;
        c_tollUserData.entryTollPointId = entryTollPointIdPtr.cast<C.TollPointID_t>();
      } else {
        c_tollUserData.entryTollPointId = nullptr;
      }

      // Handle other optional fields...
      if(entryTimeStamp != null){
        final entryTimeStampPtr = calloc<C.DDateTime>();
        entryTimeStamp!.toC(entryTimeStampPtr);
        c_tollUserData.entryTimeStamp = entryTimeStampPtr;
      } else {
        c_tollUserData.entryTimeStamp = nullptr;
      }

      if(locAndTimeStamps != null){
        final locAndTimeStampsPtr = calloc<C.LocAndTimeStamps>();
        locAndTimeStamps!.toC(locAndTimeStampsPtr);
        c_tollUserData.locAndTimeStamps = locAndTimeStampsPtr;
      } else {
        c_tollUserData.locAndTimeStamps = nullptr;
      }

      if(lastTollPoints != null){
        final lastTollPointsPtr = calloc<C.LastTollPointInfos>();
        lastTollPoints!.toC(lastTollPointsPtr);
        c_tollUserData.lastTollPoints = lastTollPointsPtr;
      } else {
        c_tollUserData.lastTollPoints = nullptr;
      }

      if(charge != null){
        final chargePtr = calloc<C.PaymentFee>();
        charge!.toC(chargePtr);
        c_tollUserData.charge = chargePtr;
      } else {
        c_tollUserData.charge = nullptr;
      }

      return c_tollUserData;
    }

    void _fillTspId(String tspId, Pointer<C.TollUserData> pointer) {
      final c_tollUserData = pointer.ref;
      
      // Clean up existing allocation
      if (c_tollUserData.tspId.buf != nullptr) {
        calloc.free(c_tollUserData.tspId.buf);
        c_tollUserData.tspId.buf = nullptr;
        c_tollUserData.tspId.size = 0;
      }
      
      // Encode the OID string to bytes
      List<int> oidBytes = _encodeOid(tspId);
      
      if (oidBytes.isNotEmpty) {
        c_tollUserData.tspId.buf = calloc<Uint8>(oidBytes.length);
        c_tollUserData.tspId.size = oidBytes.length;
        
        for (int i = 0; i < oidBytes.length; i++) {
          c_tollUserData.tspId.buf[i] = oidBytes[i];
        }
      } else {
        c_tollUserData.tspId.buf = nullptr;
        c_tollUserData.tspId.size = 0;
      }
    }

    List<int> _encodeOid(String oidString) {
      List<String> parts = oidString.split('.');
      if (parts.length < 2) return [];
      
      List<int> bytes = [];
      
      // First byte: (first * 40) + second
      int first = int.tryParse(parts[0]) ?? 0;
      int second = int.tryParse(parts[1]) ?? 0;
      bytes.add(first * 40 + second);
      
      // Encode remaining parts using variable-length encoding
      for (int i = 2; i < parts.length; i++) {
        int value = int.tryParse(parts[i]) ?? 0;
        List<int> encoded = _encodeVariableLength(value);
        bytes.addAll(encoded);
      }
      
      return bytes;
    }

    List<int> _encodeVariableLength(int value) {
      if (value == 0) return [0];
      
      List<int> bytes = [];
      while (value > 0) {
        bytes.insert(0, value & 0x7F);
        value >>= 7;
      }
      
      // Set continuation bit on all bytes except the last
      for (int i = 0; i < bytes.length - 1; i++) {
        bytes[i] |= 0x80;
      }
      
      return bytes;
    }

    void _cleanupExistingAllocations(C.TollUserData c_tollUserData) {
      // Clean up tspId
      if (c_tollUserData.tspId.buf != nullptr) {
        calloc.free(c_tollUserData.tspId.buf);
        c_tollUserData.tspId.buf = nullptr;
        c_tollUserData.tspId.size = 0;
      }
      
      // Clean up pointer fields
      if (c_tollUserData.vehType != nullptr) {
        calloc.free(c_tollUserData.vehType);
        c_tollUserData.vehType = nullptr;
      }
      
      if (c_tollUserData.vehicleDescription != nullptr) {
        calloc.free(c_tollUserData.vehicleDescription);
        c_tollUserData.vehicleDescription = nullptr;
      }
      
      if (c_tollUserData.numOccupants != nullptr) {
        calloc.free(c_tollUserData.numOccupants);
        c_tollUserData.numOccupants = nullptr;
      }
      
      if (c_tollUserData.entryTollPointId != nullptr) {
        calloc.free(c_tollUserData.entryTollPointId);
        c_tollUserData.entryTollPointId = nullptr;
      }
      
    }

    TollUserData({
      required this.timestamp,
      required this.tspId,
      required this.vehicleId,
      this.vehType,
      this.vehicleDescription,
      this.vehAxlesAndWeight,
      this.numOccupants,
      this.entryTollPointId,
      this.entryTimeStamp,
      this.locAndTimeStamps,
      this.lastTollPoints,
      this.charge
    });

    String _oidBufferToString(C.ASN__PRIMITIVE_TYPE_s oid) {
      if (oid.size == 0 || oid.buf == nullptr) {
        return "1.2.3"; // Default OID
      }
      
      try {
        List<int> bytes = [];
        for (int i = 0; i < oid.size; i++) {
          bytes.add(oid.buf[i]);
        }
        
        return _decodeOid(bytes);
      } catch (e) {
        print("Error decoding OID: $e");
        return "1.2.3"; // Fallback
      }
    }

    String _decodeOid(List<int> bytes) {
      if (bytes.isEmpty) return "1.2.3";
      
      List<int> nodes = [];
      
      // Decode first byte: (first * 40) + second
      int firstByte = bytes[0];
      int first = firstByte ~/ 40;
      int second = firstByte % 40;
      nodes.addAll([first, second]);
      
      // Decode remaining bytes using variable-length decoding
      int i = 1;
      while (i < bytes.length) {
        int value = 0;
        int currentByte;
        do {
          if (i >= bytes.length) break;
          currentByte = bytes[i++];
          value = (value << 7) | (currentByte & 0x7F);
        } while ((currentByte & 0x80) != 0);
        nodes.add(value);
      }
      
      return nodes.join('.');
    }
}



