/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j3217/2022/payment_fee.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_point_id.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/vehicle_types.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/last_toll_point_infos.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/loc_and_time_stamps.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_axles_and_weight_info.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_description.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/vehicle_id.dart'; 


class TollUserData {
    late DDateTime timeStamp; 
    late String tspId; 
    late VehicleId vehicleId; 
    VehicleTypes? vehType; 
    VehicleDescription? vehicleDescription; 
    VehicleAxlesAndWeightInfo? vehAxlesAndWeight; 
    int? numOccupants; 
    TollPointID? entryTollPointId; 
    DDateTime? entryTimeStamp; 
    LocAndTimeStamps? locAndTimeStamps; 
    LastTollPointInfos? lastTollPoints = null; 
    PaymentFee? charge = null; 
    TollUserData.fromC(C.TollUserData c_obj){
        timeStamp = DDateTime.fromC(c_obj.timeStamp);
        tspId = _oidBufferToString(c_obj.tspId);
        vehicleId = VehicleId.fromC(c_obj.vehicleId);
        if(c_obj.vehType.address != 0){
            vehType = VehicleTypes.values[c_obj.vehType.value];
        }

        if(c_obj.vehicleDescription.address != 0){
            vehicleDescription = VehicleDescription.fromC(c_obj.vehicleDescription.ref);
        }

        if(c_obj.vehAxlesAndWeight.address != 0){
            vehAxlesAndWeight = VehicleAxlesAndWeightInfo.fromC(c_obj.vehAxlesAndWeight.ref);
        }

        if(c_obj.numOccupants.address != 0){
            numOccupants = c_obj.numOccupants.value;
        }

        if(c_obj.entryTollPointId.address != 0){
            entryTollPointId = TollPointID(c_obj.entryTollPointId.value);
        }

        if(c_obj.entryTimeStamp.address != 0){
            entryTimeStamp = DDateTime.fromC(c_obj.entryTimeStamp.ref);
        }

        if(c_obj.locAndTimeStamps.address != 0){
            locAndTimeStamps = LocAndTimeStamps.fromC(c_obj.locAndTimeStamps.ref);
        }

        if(c_obj.lastTollPoints.address != 0){
            lastTollPoints = LastTollPointInfos.fromC(c_obj.lastTollPoints.ref);
        }

        if(c_obj.charge.address != 0){
            charge = PaymentFee.fromC(c_obj.charge.ref);
        }

    }

    String _oidBufferToString(C.ASN__PRIMITIVE_TYPE_s oid) {
      if (oid.size == 0 || oid.buf == nullptr) {
        return "1.2.3"; // Default OID
      }
      
      try {
        List<int> bytes = [];
        for (int i = 0; i < oid.size; i++) {
          bytes.add(oid.buf[i]);
        }
        
        return _decodeOid(bytes);
      } catch (e) {
        print("Error decoding OID: $e");
        return "1.2.3"; // Fallback
      }
    }

    String _decodeOid(List<int> bytes) {
      if (bytes.isEmpty) return "1.2.3";
      
      List<int> nodes = [];
      
      // Decode first byte: (first * 40) + second
      int firstByte = bytes[0];
      int first = firstByte ~/ 40;
      int second = firstByte % 40;
      nodes.addAll([first, second]);
      
      // Decode remaining bytes using variable-length decoding
      int i = 1;
      while (i < bytes.length) {
        int value = 0;
        int currentByte;
        do {
          if (i >= bytes.length) break;
          currentByte = bytes[i++];
          value = (value << 7) | (currentByte & 0x7F);
        } while ((currentByte & 0x80) != 0);
        nodes.add(value);
      }
      
      return nodes.join('.');
    }
}



