/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/toll_usage_message/toll_service_provider_data.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_usage_message/toll_user_data.dart';
import 'package:ffi/ffi.dart';


class TumData {
    late TollUserData tollUserData; 
    TollServiceProviderData? tollServiceProviderData; 
    TumData.fromC(C.TumData c_obj){
        tollUserData = TollUserData.fromC(c_obj.tollUserData);
        if(c_obj.tollServiceProviderData.address != 0){
            tollServiceProviderData = TollServiceProviderData(c_obj.tollServiceProviderData.ref);
        }
    }

    void toC(Pointer<C.TumData> pointer) {
      final c_tumData = pointer.ref;

      pointer.cast<Uint8>().asTypedList(sizeOf<C.TumData>()).fillRange(0, sizeOf<C.TumData>(), 0);

      final tollUserDataPtr = calloc<C.TollUserData>();

      tollUserDataPtr.cast<Uint8>().asTypedList(sizeOf<C.TollUserData>()).fillRange(0, sizeOf<C.TollUserData>(), 0);
      tollUserData.toC(tollUserDataPtr);
      c_tumData.tollUserData = tollUserDataPtr.ref;  
     

      if(tollServiceProviderData != null){
        final tollServiceProviderDataPtr = calloc<C.OCTET_STRING>();
        tollServiceProviderDataPtr.cast<Uint8>().asTypedList(sizeOf<C.OCTET_STRING>()).fillRange(0, sizeOf<C.OCTET_STRING>(), 0);
        tollServiceProviderData!.toC(tollServiceProviderDataPtr);
        c_tumData.tollServiceProviderData = tollServiceProviderDataPtr;  // This assigns the pointer
      } else {
        c_tumData.tollServiceProviderData = nullptr;
      }
    }

    void free(Pointer<C.TumData> pointer) {
      final c_tumData = pointer.ref;

      Pointer<C.TollUserData> tollUserDataPtr = Pointer<C.TollUserData>.fromAddress(pointer.address);

      tollUserData.free(tollUserDataPtr);

      if (c_tumData.tollServiceProviderData != nullptr) {
        tollServiceProviderData!.free(c_tumData.tollServiceProviderData);
        c_tumData.tollServiceProviderData = nullptr;
      }

      calloc.free(pointer);
    }

    TumData ({
      required this.tollUserData,
      this.tollServiceProviderData
    });
}
