/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:ffi';
import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/toll_usage_message/user_id.dart';


class VehicleId {
    String? vehicleIdentity; 
    String? licPlateState; 
    String? licPlateNumVeh; 
    String? licPlateNumTrailer; 
    UserId? userId; 
    VehicleId.fromC(C.TumVehicleId c_obj){
        if(c_obj.vehicleIdentity.address != 0){
            vehicleIdentity = c_obj.vehicleIdentity.ref.buf.asTypedList(c_obj.vehicleIdentity.ref.size).map((e) => e.toRadixString(16).padLeft(2, '0')).join();
        }

        if(c_obj.licPlateState.address != 0){
            licPlateState = convertIA5ToString(c_obj.licPlateState);
        }

        if(c_obj.licPlateNumVeh.address != 0){
            licPlateNumVeh = convertIA5ToString(c_obj.licPlateNumVeh);
        }

        if(c_obj.licPlateNumTrailer.address != 0){
            licPlateNumTrailer = convertIA5ToString(c_obj.licPlateNumTrailer);
        }

        if(c_obj.userId.address != 0){
            userId = UserId.fromC(c_obj.userId.ref);
        }

    }

    String? convertIA5ToString(Pointer<C.IA5String_t> ia5Ptr) {  // Changed IA5STRING_t to IA5String_t
      if (ia5Ptr.address != 0) {
          C.IA5String_t ia5 = ia5Ptr.ref;  // Changed IA5STRING_t to IA5String_t
          if (ia5.buf != nullptr && ia5.size > 0) {
              final byteList = ia5.buf.asTypedList(ia5.size);
              return String.fromCharCodes(byteList);
          }
      }
    return null;
}
}



