/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:ffi';
import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/toll_usage_message/user_id.dart';
import 'package:ffi/ffi.dart';


class VehicleId {
    String? vehicleIdentity; 
    String? licPlateState; 
    String? licPlateNumVeh; 
    String? licPlateNumTrailer; 
    UserId? userId; 
    VehicleId.fromC(C.TumVehicleId c_obj){
        if(c_obj.vehicleIdentity.address != 0){
            vehicleIdentity = c_obj.vehicleIdentity.ref.buf.asTypedList(c_obj.vehicleIdentity.ref.size).map((e) => e.toRadixString(16).padLeft(2, '0')).join();
        }

        if(c_obj.licPlateState.address != 0){
            licPlateState = convertIA5ToString(c_obj.licPlateState);
        }

        if(c_obj.licPlateNumVeh.address != 0){
            licPlateNumVeh = convertIA5ToString(c_obj.licPlateNumVeh);
        }

        if(c_obj.licPlateNumTrailer.address != 0){
            licPlateNumTrailer = convertIA5ToString(c_obj.licPlateNumTrailer);
        }

        if(c_obj.userId.address != 0){
            userId = UserId.fromC(c_obj.userId.ref);
        }

    }

    void toC(Pointer<C.TumVehicleId> pointer) {
      final c_vehicleId = pointer.ref;

      // Clean up existing allocations first
      _cleanupExistingAllocations(c_vehicleId);
      
      // Zero-initialize the struct
      pointer.cast<Uint8>().asTypedList(sizeOf<C.TumVehicleId>()).fillRange(0, sizeOf<C.TumVehicleId>(), 0);
      
      if (vehicleIdentity != null) {
        final vehicleIdentityPtr = calloc<C.OCTET_STRING>();
        vehicleIdentityPtr.cast<Uint8>().asTypedList(sizeOf<C.OCTET_STRING>()).fillRange(0, sizeOf<C.OCTET_STRING>(), 0);
        
        // Convert hex string to bytes
        final bytes = <int>[];
        for (int i = 0; i < vehicleIdentity!.length; i += 2) {
          bytes.add(int.parse(vehicleIdentity!.substring(i, i + 2), radix: 16));
        }
        if (bytes.isNotEmpty) {
          vehicleIdentityPtr.ref.buf = calloc<Uint8>(bytes.length);
          vehicleIdentityPtr.ref.size = bytes.length;
          
          for (int i = 0; i < bytes.length; i++) {
            vehicleIdentityPtr.ref.buf[i] = bytes[i];
          }
        } else {
          vehicleIdentityPtr.ref.buf = nullptr;
          vehicleIdentityPtr.ref.size = 0;
        }
        
        c_vehicleId.vehicleIdentity = vehicleIdentityPtr;

      } else {
        c_vehicleId.vehicleIdentity = nullptr;
      }
      
      if (licPlateState != null) {
        final licPlateStatePtr = calloc<C.IA5String_t>();
        licPlateStatePtr.cast<Uint8>().asTypedList(sizeOf<C.IA5String_t>()).fillRange(0, sizeOf<C.IA5String_t>(), 0);
        _stringToIA5String(licPlateState!, licPlateStatePtr);
        c_vehicleId.licPlateState = licPlateStatePtr;
      } else {
        c_vehicleId.licPlateState = nullptr;
      }
      
      if (licPlateNumVeh != null) {
        final licPlateNumVehPtr = calloc<C.IA5String_t>();
        licPlateNumVehPtr.cast<Uint8>().asTypedList(sizeOf<C.IA5String_t>()).fillRange(0, sizeOf<C.IA5String_t>(), 0);
        _stringToIA5String(licPlateNumVeh!, licPlateNumVehPtr);
        c_vehicleId.licPlateNumVeh = licPlateNumVehPtr;
      } else {
        c_vehicleId.licPlateNumVeh = nullptr;
      }
      
      if (licPlateNumTrailer != null) {
        final licPlateNumTrailerPtr = calloc<C.IA5String_t>();
        licPlateNumTrailerPtr.cast<Uint8>().asTypedList(sizeOf<C.IA5String_t>()).fillRange(0, sizeOf<C.IA5String_t>(), 0);
        _stringToIA5String(licPlateNumTrailer!, licPlateNumTrailerPtr);
        c_vehicleId.licPlateNumTrailer = licPlateNumTrailerPtr;
      } else {
        c_vehicleId.licPlateNumTrailer = nullptr;
      }
      
      if (userId != null) {
        final userIdPtr = calloc<C.UserId>();
        userIdPtr.cast<Uint8>().asTypedList(sizeOf<C.UserId>()).fillRange(0, sizeOf<C.UserId>(), 0);
        userId!.toC(userIdPtr);
        c_vehicleId.userId = userIdPtr;
      } else {
        c_vehicleId.userId = nullptr;
      }
    }

    void _stringToIA5String(String str, Pointer<C.IA5String_t> ia5Ptr) {
      List<int> bytes = str.codeUnits;
      
      if (bytes.isNotEmpty) {
        ia5Ptr.ref.buf = calloc<Uint8>(bytes.length);
        ia5Ptr.ref.size = bytes.length;
        
        for (int i = 0; i < bytes.length; i++) {
          ia5Ptr.ref.buf[i] = bytes[i];
        }
      } else {
        ia5Ptr.ref.buf = nullptr;
        ia5Ptr.ref.size = 0;
      }
    }

      void _cleanupExistingAllocations(C.TumVehicleId c_vehicleId) {
        // Clean up vehicleIdentity
        if (c_vehicleId.vehicleIdentity != nullptr) {
          if (c_vehicleId.vehicleIdentity.ref.buf != nullptr) {
            calloc.free(c_vehicleId.vehicleIdentity.ref.buf);
            c_vehicleId.vehicleIdentity.ref.buf = nullptr;
            c_vehicleId.vehicleIdentity.ref.size = 0;
          }
          calloc.free(c_vehicleId.vehicleIdentity);
          c_vehicleId.vehicleIdentity = nullptr;
        }
        
        // Clean up licPlateState
        if (c_vehicleId.licPlateState != nullptr) {
          if (c_vehicleId.licPlateState.ref.buf != nullptr) {
            calloc.free(c_vehicleId.licPlateState.ref.buf);
            c_vehicleId.licPlateState.ref.buf = nullptr;
            c_vehicleId.licPlateState.ref.size = 0;
          }
          calloc.free(c_vehicleId.licPlateState);
          c_vehicleId.licPlateState = nullptr;
        }
        
        // Clean up licPlateNumVeh
        if (c_vehicleId.licPlateNumVeh != nullptr) {
          if (c_vehicleId.licPlateNumVeh.ref.buf != nullptr) {
            calloc.free(c_vehicleId.licPlateNumVeh.ref.buf);
            c_vehicleId.licPlateNumVeh.ref.buf = nullptr;
            c_vehicleId.licPlateNumVeh.ref.size = 0;
          }
          calloc.free(c_vehicleId.licPlateNumVeh);
          c_vehicleId.licPlateNumVeh = nullptr;
        }
        
        // Clean up licPlateNumTrailer
        if (c_vehicleId.licPlateNumTrailer != nullptr) {
          if (c_vehicleId.licPlateNumTrailer.ref.buf != nullptr) {
            calloc.free(c_vehicleId.licPlateNumTrailer.ref.buf);
            c_vehicleId.licPlateNumTrailer.ref.buf = nullptr;
            c_vehicleId.licPlateNumTrailer.ref.size = 0;
          }
          calloc.free(c_vehicleId.licPlateNumTrailer);
          c_vehicleId.licPlateNumTrailer = nullptr;
        }
        
        // Clean up userId
        if (c_vehicleId.userId != nullptr) {
          calloc.free(c_vehicleId.userId);
          c_vehicleId.userId = nullptr;
        }
      }
    
    VehicleId.fromDetails(String vehicleIdentity, String licPlateState, String licPlateNumVeh){
        this.vehicleIdentity = vehicleIdentity;
        this.licPlateState = licPlateState;
        this.licPlateNumVeh = licPlateNumVeh;
    }

    String? convertIA5ToString(Pointer<C.IA5String_t> ia5Ptr) {  // Changed IA5STRING_t to IA5String_t
      if (ia5Ptr.address != 0) {
          C.IA5String_t ia5 = ia5Ptr.ref;  // Changed IA5STRING_t to IA5String_t
          if (ia5.buf != nullptr && ia5.size > 0) {
              final byteList = ia5.buf.asTypedList(ia5.size);
              return String.fromCharCodes(byteList);
          }
      }
    return null;
  }

}



