/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/choice/choice_network_charge_table.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/entry_charges_table.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/exit_charges_table.dart';


class ClosedNetworkChargesTable{
  late ClosedNetworkChargesTableChoice closedNetworkChargesTable;
  
  ClosedNetworkChargesTable.fromC(C.ClosedNetworkChargesTable c_obj){
    closedNetworkChargesTable = ClosedNetworkChargesTableChoice.fromC(c_obj);
  }
}

class ClosedNetworkChargesTableChoice{ 
  late Choice_NetworkChargeTable closedNetworkChargesTableChoice;
  ClosedNetworkChargesTableChoice.fromC(C.ClosedNetworkChargesTable c_closedNetworkChargesTable) {
    if (c_closedNetworkChargesTable.present == C.ClosedNetworkChargesTable_PR.ClosedNetworkChargesTable_PR_entryChargesTable) {
      closedNetworkChargesTableChoice = EntryChargesTable.fromC(c_closedNetworkChargesTable.choice.entryChargesTable);
    } else if (c_closedNetworkChargesTable.present == C.ClosedNetworkChargesTable_PR.ClosedNetworkChargesTable_PR_exitChargesTable) {
      closedNetworkChargesTableChoice = ExitChargesTable.fromC(c_closedNetworkChargesTable.choice.exitChargesTable);
    }
  }
}
