/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/payment_fee.dart'; 


class OperatorDefined{
    PaymentFee? opDefCharge1; 
    PaymentFee? opDefCharge2; 
    PaymentFee? opDefCharge3; 
    PaymentFee? opDefCharge4; 
    PaymentFee? opDefCharge5; 
    PaymentFee? opDefCharge6; 
    PaymentFee? opDefCharge7; 
    PaymentFee? opDefCharge8; 
    PaymentFee? opDefCharge9; 
    PaymentFee? opDefCharge10; 
    PaymentFee? opDefCharge11; 
    PaymentFee? opDefCharge12; 
    PaymentFee? opDefCharge13; 
    PaymentFee? opDefCharge14; 
    PaymentFee? opDefCharge15; 
    PaymentFee? opDefCharge16; 
    OperatorDefined.fromC(C.OperatorDefined c_obj){
        if(c_obj.opDefCharge1.address != 0){
            opDefCharge1 = PaymentFee.fromC(c_obj.opDefCharge1.ref);
        }

        if(c_obj.opDefCharge2.address != 0){
            opDefCharge2 = PaymentFee.fromC(c_obj.opDefCharge2.ref);
        }

        if(c_obj.opDefCharge3.address != 0){
            opDefCharge3 = PaymentFee.fromC(c_obj.opDefCharge3.ref);
        }

        if(c_obj.opDefCharge4.address != 0){
            opDefCharge4 = PaymentFee.fromC(c_obj.opDefCharge4.ref);
        }

        if(c_obj.opDefCharge5.address != 0){
            opDefCharge5 = PaymentFee.fromC(c_obj.opDefCharge5.ref);
        }

        if(c_obj.opDefCharge6.address != 0){
            opDefCharge6 = PaymentFee.fromC(c_obj.opDefCharge6.ref);
        }

        if(c_obj.opDefCharge7.address != 0){
            opDefCharge7 = PaymentFee.fromC(c_obj.opDefCharge7.ref);
        }

        if(c_obj.opDefCharge8.address != 0){
            opDefCharge8 = PaymentFee.fromC(c_obj.opDefCharge8.ref);
        }

        if(c_obj.opDefCharge9.address != 0){
            opDefCharge9 = PaymentFee.fromC(c_obj.opDefCharge9.ref);
        }

        if(c_obj.opDefCharge10.address != 0){
            opDefCharge10 = PaymentFee.fromC(c_obj.opDefCharge10.ref);
        }

        if(c_obj.opDefCharge11.address != 0){
            opDefCharge11 = PaymentFee.fromC(c_obj.opDefCharge11.ref);
        }

        if(c_obj.opDefCharge12.address != 0){
            opDefCharge12 = PaymentFee.fromC(c_obj.opDefCharge12.ref);
        }

        if(c_obj.opDefCharge13.address != 0){
            opDefCharge13 = PaymentFee.fromC(c_obj.opDefCharge13.ref);
        }

        if(c_obj.opDefCharge14.address != 0){
            opDefCharge14 = PaymentFee.fromC(c_obj.opDefCharge14.ref);
        }

        if(c_obj.opDefCharge15.address != 0){
            opDefCharge15 = PaymentFee.fromC(c_obj.opDefCharge15.ref);
        }

        if(c_obj.opDefCharge16.address != 0){
            opDefCharge16 = PaymentFee.fromC(c_obj.opDefCharge16.ref);
        }

    }
}
