/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/payment_fee.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/operator_defined.dart';


class SpecialCharges{
    PaymentFee? hov2Charge = null; 
    PaymentFee? hov3Charge = null; 
    PaymentFee? hov4Charge = null; 
    PaymentFee? hov5PlusCharge = null; 
    PaymentFee? cleanAirCharge = null; 
    OperatorDefined? operatorDefined = null; 
    EngineCharacteristics? engineCharacteristics = null; 
    SpecialCharges.fromC(C.SpecialCharges c_obj){
        if(c_obj.hov2Charge.address != 0){
            hov2Charge = PaymentFee.fromC(c_obj.hov2Charge.ref);
        }

        if(c_obj.hov3Charge.address != 0){
            hov3Charge = PaymentFee.fromC(c_obj.hov3Charge.ref);
        }

        if(c_obj.hov4Charge.address != 0){
            hov4Charge = PaymentFee.fromC(c_obj.hov4Charge.ref);
        }

        if(c_obj.hov5PlusCharge.address != 0){
            hov5PlusCharge = PaymentFee.fromC(c_obj.hov5PlusCharge.ref);
        }

        if(c_obj.cleanAirCharge.address != 0){
            cleanAirCharge = PaymentFee.fromC(c_obj.cleanAirCharge.ref);
        }

        if(c_obj.operatorDefined.address != 0){
            operatorDefined = OperatorDefined.fromC(c_obj.operatorDefined.ref);
        }

        if(c_obj.engineCharacteristics.address != 0){
            engineCharacteristics = EngineCharacteristics(c_obj.engineCharacteristics.value);
        }

    }
}

class EngineCharacteristics{
  late int engineCharacteristics;
  EngineCharacteristics(int value): engineCharacteristics = value;
}
