/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/ack_policy.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_charger_info.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_point_map.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/tum_instructions.dart';



class TollAdvertisementInfo{
    late MsgCount tamSequenceNum; 
    late TotalTamsInteger totalTams; 
    late TamNumInteger tamNum; 
    late TollChargerInfo tollChargerInfo; 
    late DDateTime timestamp; 
    TumInstructions? tumInstructions; 
    late TollPointMap tollPointMap; 
    late TumPublicKeyOctetString tumPublicKey; 
    late AckPolicy ackPolicy; 
    bool? lastTollPtDataReq; 
    TollAdvertisementInfo.fromC(C.TollAdvertisementInfo c_obj){
        tamSequenceNum = MsgCount(c_obj.tamSequenceNum);
        totalTams = TotalTamsInteger(c_obj.totalTams);
        tamNum = TamNumInteger(c_obj.tamNum);
        tollChargerInfo = TollChargerInfo.fromC(c_obj.tollChargerInfo);
        timestamp = DDateTime.fromC(c_obj.timestamp);
        if(c_obj.tumInstructions.address != 0){
          tumInstructions = TumInstructions.fromC(c_obj.tumInstructions.ref);
        }

        tollPointMap = TollPointMap.fromC(c_obj.tollPointMap);
        tumPublicKey = TumPublicKeyOctetString(c_obj.tumPublicKey);
        ackPolicy = AckPolicy.fromC(c_obj.ackPolicy);
        if(c_obj.lastTollPtDataReq.address != 0){
          lastTollPtDataReq = c_obj.lastTollPtDataReq.value == 1;
        }

    }
}
class TotalTamsInteger {
    late int totalTamsInteger;
    TotalTamsInteger(int value): totalTamsInteger = value;
}


class TamNumInteger {
    late int tamNumInteger;
    TamNumInteger(int value): tamNumInteger = value;
}


class TumPublicKeyOctetString {
    late C.OCTET_STRING_t tumPublicKeyOctetString;
    TumPublicKeyOctetString(C.OCTET_STRING_t value): tumPublicKeyOctetString = value;
}


