/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/descriptive_name.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_point_id.dart';
import 'package:ffi/ffi.dart';


class TollChargerInfo{
    late String tollChargerId;
    late TollPointID tollPointId; 
    DescriptiveName? descriptiveName; 

    TollChargerInfo.fromC(C.TollChargerInfo c_obj){
        tollChargerId = _oidBufferToString(c_obj.tollChargerId);
        tollPointId = TollPointID(c_obj.tollPointId);
        if(c_obj.descriptiveName.address != 0){
            descriptiveName = DescriptiveName.fromOctetString(c_obj.descriptiveName.ref);
        }
    }

    void toC(Pointer<C.TollChargerInfo> pointer) {
      final c_info = pointer.ref;
      
      _fillTollChargerId(tollChargerId, pointer);
      c_info.tollPointId = tollPointId.tollPointID;

      // Clean up existing descriptiveName allocation first
      if (c_info.descriptiveName != nullptr) {
        calloc.free(c_info.descriptiveName);
        c_info.descriptiveName = nullptr;
      }
      
      if(descriptiveName != null){
        final descriptiveNamePtr = calloc<C.OCTET_STRING>();
        descriptiveName!.toC(descriptiveNamePtr);
        c_info.descriptiveName = descriptiveNamePtr;
      } else {
        c_info.descriptiveName = nullptr;
      }
    }

    String _oidBufferToString(C.ASN__PRIMITIVE_TYPE_s oid) {
      if (oid.size == 0 || oid.buf == nullptr) {
        return "1.2.3"; // Default OID
      }
      
      try {
        List<int> bytes = [];
        for (int i = 0; i < oid.size; i++) {
          bytes.add(oid.buf[i]);
        }
        
        return _decodeOid(bytes);
      } catch (e) {
        print("Error decoding OID: $e");
        return "1.2.3"; // Fallback
      }
    }

    String _decodeOid(List<int> bytes) {
      if (bytes.isEmpty) return "1.2.3";
      
      List<int> nodes = [];
      
      // Decode first byte: (first * 40) + second
      int firstByte = bytes[0];
      int first = firstByte ~/ 40;
      int second = firstByte % 40;
      nodes.addAll([first, second]);
      
      // Decode remaining bytes using variable-length decoding
      int i = 1;
      while (i < bytes.length) {
        int value = 0;
        int currentByte;
        do {
          if (i >= bytes.length) break;
          currentByte = bytes[i++];
          value = (value << 7) | (currentByte & 0x7F);
        } while ((currentByte & 0x80) != 0);
        nodes.add(value);
      }
      
      return nodes.join('.');
    }

    void _fillTollChargerId(String oidString, Pointer<C.TollChargerInfo> tollChargerInfoPtr) {
      final tollChargerIdField = tollChargerInfoPtr.ref.tollChargerId;
      
      // Free existing buffer if present
      if (tollChargerIdField.buf != nullptr) {
        calloc.free(tollChargerIdField.buf);
        tollChargerIdField.buf = nullptr;
        tollChargerIdField.size = 0;
      }
      
      // Encode OID
      List<String> nodeStrings = oidString.split('.');
      if (nodeStrings.length < 2) {
        return; // Leave empty on invalid OID
      }
      
      List<int> nodes = nodeStrings.map(int.parse).toList();
      List<int> encodedBytes = [];
      
      int firstByte = (nodes[0] * 40) + nodes[1];
      encodedBytes.add(firstByte);
      
      for (int i = 2; i < nodes.length; i++) {
        int value = nodes[i];
        List<int> tempBytes = [];
        
        do {
          tempBytes.insert(0, value & 0x7F);
          value >>= 7;
        } while (value > 0);
        
        for (int j = 0; j < tempBytes.length - 1; j++) {
          tempBytes[j] |= 0x80;
        }
        
        encodedBytes.addAll(tempBytes);
      }
      
      // Fill the struct field directly
      tollChargerInfoPtr.ref.tollChargerId.size = encodedBytes.length;
      tollChargerInfoPtr.ref.tollChargerId.buf = calloc<Uint8>(encodedBytes.length);
      
      for (int i = 0; i < encodedBytes.length; i++) {
        tollChargerInfoPtr.ref.tollChargerId.buf[i] = encodedBytes[i];
      }
    }

    void stringToAsnPrimitiveType(String oidString, Pointer<C.ASN__PRIMITIVE_TYPE_s> target) {
      List<String> nodeStrings = oidString.split('.');
      if (nodeStrings.length < 2) {
        throw ArgumentError("Invalid OID string: $oidString");
      }
      
      List<int> nodes = nodeStrings.map(int.parse).toList();
      
      // Free existing buffer if present
      if (target.ref.buf != nullptr) {
        calloc.free(target.ref.buf);
      }
      
      // Encode OID bytes (your existing logic is correct)
      List<int> encodedBytes = [];
      int firstByte = (nodes[0] * 40) + nodes[1];
      encodedBytes.add(firstByte);
      
      for (int i = 2; i < nodes.length; i++) {
        int value = nodes[i];
        List<int> tempBytes = [];
        
        do {
          tempBytes.insert(0, value & 0x7F);
          value >>= 7;
        } while (value > 0);
        
        for (int j = 0; j < tempBytes.length - 1; j++) {
          tempBytes[j] |= 0x80;
        }
        
        encodedBytes.addAll(tempBytes);
      }
      
      // Fill the target struct
      target.ref.size = encodedBytes.length;
      target.ref.buf = calloc<Uint8>(encodedBytes.length);
      
      for (int i = 0; i < encodedBytes.length; i++) {
        target.ref.buf[i] = encodedBytes[i];
      }
    }   
}
