/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;


class TumInstructions{
    late MaxNumOfLocTimeStampsInteger maxNumOfLocTimeStamps; 
    late LocTimeStampRateInteger locTimeStampRate; 
    TumInstructions.fromC(C.TumInstructions c_obj){
        maxNumOfLocTimeStamps = MaxNumOfLocTimeStampsInteger(c_obj.maxNumOfLocTimeStamps);
        locTimeStampRate = LocTimeStampRateInteger(c_obj.locTimeStampRate);
    }
}
class MaxNumOfLocTimeStampsInteger{
    late int maxNumOfLocTimeStampsInteger;
    MaxNumOfLocTimeStampsInteger(int value): maxNumOfLocTimeStampsInteger = value <= 5 ? value : 5; //integer 1-5
}


class LocTimeStampRateInteger{
    late int locTimeStampRateInteger;
    LocTimeStampRateInteger(int value): locTimeStampRateInteger = value <= 10 ? value : 10; //integer 1-10
}


