/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/payment_fee.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/special_charges.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/vehicle_types.dart';


class VehTypeCharges {
    late VehicleTypes vehType; 
    late PaymentFee charges; 
    SpecialCharges? specialCharges; 
    VehTypeCharges.fromC(C.VehTypeCharges c_obj){
      vehType = VehicleTypes.values[c_obj.vehType - 1];
      charges = PaymentFee.fromC(c_obj.charges);
      if(c_obj.specialCharges.address != 0){
          specialCharges = SpecialCharges.fromC(c_obj.specialCharges.ref);
      }
    }
}
