/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:convert';
import 'dart:typed_data';

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j2735/2024/common/temporary_id.dart';


class TumAckHash{
    SignedTumHash? signedTumHash; 
    late TemporaryID tempId; 
    late MsgCount tumSequenceNum; 
    TumAckHash.fromC(C.TumAckHash c_obj){
        if(c_obj.signedTumHash.address != 0){
            signedTumHash = SignedTumHash.fromOctetString(c_obj.signedTumHash.ref);
        }

        tempId = TemporaryID.fromOctetString(c_obj.tempId);
        tumSequenceNum = MsgCount(c_obj.tumSequenceNum);
    }
}

class SignedTumHash{
  String? signedTumHash;

  SignedTumHash.fromOctetString(C.OCTET_STRING string ){
    final Uint8List byteList = string.buf.asTypedList(string.size);

    signedTumHash = utf8.decode(byteList);
  }
}


